---
- name: create arma 3 server configuration file
  template:
    src: server.cfg.j2
    dest: "{{ steamcmd_user_home }}server.cfg"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0600'