---
- name: add i386 architecture
  shell: dpkg --add-architecture i386

- name: create user for steamcmd
  user:
    name: "{{ steamcmd_user }}"
    state: present
    comment: User for Steam/SteamCMD

- name: install dependencies for SteamCMD and other useful packages
  apt:
    update_cache: yes
    pkg:
    - lib32gcc1
    - lib32stdc++6
    - python3
    - fail2ban
    - rename
    - htop
    - nethogs
    - ufw

- name: create Arma profiles directorys
  file: 
    path: "{{ steamcmd_user_home }}.local/share/{{ item }}" 
    state: directory
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
  with_items:
    - "Arma 3"
    - "Arma 3 - Other Profiles"
    - "Arma 3 - Other Profiles/server"

- name: create steamcmd directory
  file:
    path: "{{ steamcmd_directory }}"
    state: directory
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: unzip steamcmd tar
  unarchive:
    src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
    dest: "{{ steamcmd_directory }}"
    remote_src: yes
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: Set steam user permissions
  file:
    path: "{{ steamcmd_user_home }}"
    recurse: yes
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: set steamcmd as executable
  file:
    path: "{{ steamcmd_directory }}steamcmd.sh"
    mode: +x
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: open firewall ports
  ufw:
    rule: allow
    port: 2302:2304 #Client, Steam Query, Steam Master
    proto: udp

- name: Run SteamCMD and Install ARMA (Will take a long time on first run)
  command: "{{ steamcmd_directory }}steamcmd.sh +login {{ steam_username }} {{ steam_password }} {{steam_guard}} +force_install_dir {{ steam_server_directory }} +app_update 233780 +quit"
  register: output
  become: yes
  become_user: "{{ steamcmd_user }}"

- name: Copy start.sh to server
  copy:
    src: start.sh
    dest: "{{ steam_server_directory }}start.sh"
    mode: +x
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"

- name: Start ARMA Server with Screen
  command: "{{ steam_server_directory }}start.sh"  #this is not starting a screen session for some reason
  register: output
  become: yes
  become_user: "{{ steamcmd_user }}"

- name: Get server IP Address
  ipify_facts:

- name: Arma Server is Ready
  debug: 
    msg: Your ARMA server is ready! You can connect to it directly on the following IP {{ ipify_public_ip }}