---
- name: Add multiverse repo for 64 bit 
  apt_repository:
    repo: multiverse

- name: Add i386 architecture
  command: dpkg --add-architecture i386

- name: Create steam user
  user:
    name: steam
    comment: User for Steam/SteamCMD

- name: Install dependencies for SteamCMD
  apt:
    pkg:
    - lib32gcc1
    - lib32stdc++6

- name: unzip steamcmd tar
  unarchive:
    src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz #maybe make this a var, but I don't think this changes
    dest: /home/steamcmd #change this to a better dest
    remote_src: yes
