---
- name: add i386 architecture
  shell: dpkg --add-architecture i386

- name: create steam user
  user:
    name: steam
    state: present
    comment: User for Steam/SteamCMD

- name: install dependencies for SteamCMD
  apt:
    update_cache: yes
    pkg:
    - lib32gcc1
    - lib32stdc++6
    - python
    - fail2ban

- name: create Arma profiles directory
  file: path="/home/steam/.local/share/{{ item }}" state=directory
  with_items:
    - "Arma 3"
    - "Arma 3 - Other Profiles"
    - "Arma 3 - Other Profiles/server"

- name: create steamcmd dir
  file:
    path: /home/steam/steamcmd
    state: directory

- name: unzip steamcmd tar
  unarchive:
    src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
    dest: /home/steam/steamcmd
    remote_src: yes

- name: set steamcmd as executable
  file:
    path: /home/steam/steamcmd/steamcmd.sh 
    mode: +x

- name: open firewall ports
  ufw:
    rule: allow
    port: 2302:2304 #Client, Steam Query, Steam Master
    proto: udp

- name: Run SteamCMD and Install ARMA
  shell: "./steamcmd.sh +login {{ steam_username }} {{ steam_password }} +force_install_dir ../arma3 +app_update 233780 +quit"
  args:
    chdir: /home/steam/steamcmd
